# Generated by Django 4.2.11 on 2024-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('fa_string', models.SlugField(max_length=100)),
                ('colour', models.CharField(max_length=7)),
            ],
        ),
    ]
