# Generated by Django 4.2.11 on 2024-03-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0004_alter_defect_latest_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='reoccurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='defect',
            name='updates_count',
            field=models.IntegerField(default=0),
        ),
    ]
