# Generated by Django 4.2.11 on 2024-03-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0008_alter_update_options_alter_update_update_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='excerpt',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='defect',
            name='excerpt',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
