# Generated by Django 4.2.11 on 2024-03-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0009_update_excerpt_alter_defect_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='trunc_title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
