# Generated by Django 4.2.11 on 2024-03-25 14:42

import defect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0010_defect_trunc_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(defect.models.get_null_category), related_name='defects', to='defect.category'),
        ),
    ]
