# Generated by Django 4.2.11 on 2024-03-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0011_alter_defect_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='defect.category'),
        ),
    ]
