# Generated by Django 4.2.11 on 2024-03-25 16:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0012_alter_defect_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='update',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
