# Generated by Django 4.2.11 on 2024-03-25 18:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0013_defect_image_url_update_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='update',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
