# Generated by Django 4.2.11 on 2024-03-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect', '0014_alter_defect_image_url_alter_update_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Resolved')], default=0),
        ),
        migrations.AlterField(
            model_name='update',
            name='resolution',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Resolved')], default=0),
        ),
    ]
